In [ ]:
import numpy as np
import tensorflow as tf

c:\users\thomas\miniconda3\envs\ml\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
arr = np.array([[1.],[2.],[3.],[4.],[5.],[6.],[7.],[8.],[9.],[10.],[11.],[12.],[13.],[14.],[15.],[16.]])
print(arr.shape)
print(arr)
rs = np.reshape(arr, [-1, 4, 1])
print(rs.shape)
print(rs)

(16, 1)
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [15.]
 [16.]]
(4, 4, 1)
[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [10.]
  [11.]
  [12.]]

 [[13.]
  [14.]
  [15.]
  [16.]]]


In [25]:
with tf.Session() as sess:
    _input = tf.placeholder(tf.float32, (None, 1))
    reshape = tf.reshape(_input, [-1, 4, 1])
    print("RESHAPE:")
    output = sess.run(reshape, {_input: arr})
    print(output.shape)
    print(output)
    
    print("SPLIT:")
    split1, split2 = tf.split(reshape, num_or_size_splits=2)
    print("split 1")
    output = sess.run(tf.reduce_max(split1, axis=1), {_input: arr})
    print(output.shape)
    print(output)
    print("split 2")
    output = sess.run(split2, {_input: arr})
    print(output.shape)
    print(output)
    

    

RESHAPE:
(4, 4, 1)
[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [10.]
  [11.]
  [12.]]

 [[13.]
  [14.]
  [15.]
  [16.]]]
SPLIT:
split 1
(2, 1)
[[4.]
 [8.]]
split 2
(2, 4, 1)
[[[ 9.]
  [10.]
  [11.]
  [12.]]

 [[13.]
  [14.]
  [15.]
  [16.]]]
